spawn:
  x: 0
  y: 40
  z: 0
  yaw: 180
  pitch: 0
  world: spawn
arena:
  name: arena
webhooks:
  reports: https://discord.com/api/webhooks/901630567391588432/yesf6CvK_uNKW3FCoCALkeIf_eDutkJibhgl1p6Kev7qwKfLJXOWd4bwyIDuIJ5WPQmC
  bans: https://discord.com/api/webhooks/901630631249838081/54cm-IvK6usqizC6zG28WV6ZRUPEKauRQ-fLQxUAfOiEi_8AEYBJkkRYJexrc_rwNGiK
  logs: https://discord.com/api/webhooks/901630685960339477/4O-IyMpMBfRMvQg_9mKhaINP3vBAZNhj3aRPG2269OxkXe7WbYMYdLMkdlmTChu7D8HA